# Generated by Django 5.2.7 on 2025-11-10 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_usuario_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the organization is active'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(help_text='10-digit phone number', max_length=9, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{9}$')]),
        ),
    ]
