# Generated by Django 5.2.7 on 2025-10-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('name', models.CharField(max_length=140)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Nivel de severidad de la alerta.', max_length=10)),
                ('unit', models.CharField(default='kWh', help_text='Unidad por defecto (kWh, W, A, etc.).', max_length=32)),
                ('default_min_threshold', models.FloatField(blank=True, help_text='Umbral mínimo por defecto.', null=True)),
                ('default_max_threshold', models.FloatField(blank=True, help_text='Umbral máximo por defecto.', null=True)),
            ],
            options={
                'db_table': 'alert_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(help_text='Código único de inventario (SKU).', max_length=80, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('nominal_voltage_v', models.FloatField(blank=True, null=True)),
                ('max_current_a', models.FloatField(blank=True, null=True)),
                ('standby_power_w', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Categoría del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='devices.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('min_threshold', models.FloatField(blank=True, help_text='Umbral mínimo (override).', null=True)),
                ('max_threshold', models.FloatField(blank=True, help_text='Umbral máximo (override).', null=True)),
                ('unit_override', models.CharField(blank=True, help_text='Unidad específica (opcional).', max_length=32, null=True)),
                ('alert_rule', models.ForeignKey(help_text='Regla de alerta aplicada a este producto.', on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_links', to='devices.alertrule')),
                ('product', models.ForeignKey(help_text='Producto al que se aplica la alerta con umbrales específicos.', on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_links', to='devices.product')),
            ],
            options={
                'db_table': 'product_alert_rule',
                'ordering': ['product_id', 'alert_rule_id'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Productos a los que aplica esta regla (relación N:M con umbrales por producto).', related_name='alert_rules', through='devices.ProductAlertRule', to='devices.product'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('name', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(help_text='Organización (cliente) propietaria de la zona.', on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'zone',
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('name', models.CharField(help_text='Nombre legible único dentro de la organización.', max_length=160)),
                ('max_power_w', models.PositiveIntegerField(help_text='Potencia máxima (W) para validaciones/reportes.')),
                ('image', models.ImageField(blank=True, help_text='Imagen opcional del dispositivo.', null=True, upload_to='devices/')),
                ('serial_number', models.CharField(blank=True, help_text='N° de serie (opcional).', max_length=120)),
                ('organization', models.ForeignKey(help_text='Organización (cliente) dueña del dispositivo.', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.organization')),
                ('product', models.ForeignKey(help_text='Producto del que deriva este dispositivo concreto.', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.product')),
                ('zone', models.ForeignKey(help_text='Zona donde está instalado el dispositivo.', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.zone')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se generó el evento de alerta.')),
                ('message', models.CharField(blank=True, help_text='Mensaje adicional (opcional).', max_length=240)),
                ('alert_rule', models.ForeignKey(help_text='Regla de alerta que se disparó.', on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='devices.alertrule')),
                ('device', models.ForeignKey(help_text='Dispositivo donde ocurrió la alerta.', on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='devices.device')),
            ],
            options={
                'verbose_name': 'Alert Event',
                'verbose_name_plural': 'Alert Events',
                'db_table': 'alert_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['device', 'occurred_at'], name='alert_event_device__ea6084_idx'), models.Index(fields=['alert_rule'], name='alert_event_alert_r_b494ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de creación (solo se setea una vez).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha/hora de última actualización.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Marca de borrado lógico; no elimina físicamente el registro.', null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se registró la medición.')),
                ('energy_kwh', models.FloatField(help_text='Energía medida (kWh).')),
                ('device', models.ForeignKey(help_text='Dispositivo al que pertenece la medición.', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device')),
                ('triggered_alert', models.ForeignKey(blank=True, help_text='Regla de alerta que coincidió con esta medición (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_measurements', to='devices.alertrule')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'db_table': 'measurement',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['device', 'measured_at'], name='measurement_device__c1b88c_idx'), models.Index(fields=['triggered_alert'], name='measurement_trigger_5b5387_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_afe0af_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['product'], name='product_ale_product_01a756_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['alert_rule'], name='product_ale_alert_r_acd589_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['product', 'alert_rule'], name='product_ale_product_fca7e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalertrule',
            constraint=models.UniqueConstraint(fields=('product', 'alert_rule'), name='uix_product_alert_unique'),
        ),
        migrations.AddConstraint(
            model_name='productalertrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_threshold__isnull', True), ('max_threshold__isnull', True), ('min_threshold__lte', models.F('max_threshold')), _connector='OR'), name='par_min_lte_max'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['severity'], name='alert_rule_severit_cc978d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['name'], name='alert_rule_name_3749b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.CheckConstraint(condition=models.Q(('default_min_threshold__isnull', True), ('default_max_threshold__isnull', True), ('default_min_threshold__lte', models.F('default_max_threshold')), _connector='OR'), name='alert_rule_default_min_lte_max'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together={('name', 'severity')},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'name'], name='device_organiz_34663d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['zone'], name='device_zone_id_b296ed_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['product'], name='device_product_714eb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('organization', 'name')},
        ),
    ]
